name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  benchmark:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Upgrade pip and install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Checkout EcOps action
      uses: actions/checkout@v4
      with:
        repository: CarlosPHN/EcOps
        token: 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
        path: ecops-action

    - name: Start EcOps Measurement
      uses: ./ecops-action
      with:
        method: start_measurement
        args: perf power/energy-cores/ power/energy-pkg/ 50

    - name: Run benchmark tests
      run: |
        pytest --benchmark-only --benchmark-save=benchmark_run

    - name: End EcOps Measurement
      uses: ./ecops-action
      with:
        method: end_measurement

    - name: Upload EcOps artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ecops-artifacts
        path: |
          ecops-summary.md
            ecops-result.json
