name: Benchmark
'on':
  push: {}
jobs:
  benchmark_9:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
  benchmark_8:
    runs-on: self-hosted
    needs: benchmark_9
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
  benchmark_7:
    runs-on: self-hosted
    needs: benchmark_8
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
  benchmark_6:
    runs-on: self-hosted
    needs: benchmark_7
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
  benchmark_5:
    runs-on: self-hosted
    needs: benchmark_6
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
  benchmark_4:
    runs-on: self-hosted
    needs: benchmark_5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
  benchmark_3:
    runs-on: self-hosted
    needs: benchmark_4
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
  benchmark_2:
    runs-on: self-hosted
    needs: benchmark_3
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
  benchmark_1:
    runs-on: self-hosted
    needs: benchmark_2
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
  benchmark:
    runs-on: self-hosted
    needs: benchmark_1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upgrade pip and install dependencies
      run: |-
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: ~/runner-config/scripts/setup.sh "start_measurement" "baseline=true" "benchmark_3"
        "software" perf "interval=10" "events=power/energy-pkg/,power/energy-cores/"
    - name: Run benchmark tests
      run: pytest --benchmark-only --benchmark-save=benchmark_run
    - run: ~/runner-config/scripts/setup.sh "end_measurement" "benchmark_3"
