name: Refactor
'on':
  push: {}
jobs:
  refactorjob:
    runs-on: self-hosted
    steps:
    - run: ~/runner-config/scripts/refactor.sh greencoderefactor-python "ExplicitRaiseToExceptBodyTransformer,UnusedLocalVariablesTransformer,UnusedAssignmentTransformer"
